config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  get 'search/do_search'
  post 'search/do_search'

  get 'reserve_ticket/reserve'
  post 'reserve_ticket/do_reserve'

  get 'event_share/share'
  post 'event_share/do_share'
  post 'event_share/post_feedback'

  get 'student_admin/student_login'
  get 'student_admin/student_edit'
  get 'student_admin/logout'
  post 'student_admin/login'

  get 'club_admin/club_edit'
  get 'club_admin/club_post'
  get 'club_admin/club_login'
  post 'club_admin/login'
  get 'club_admin/logout'
  post 'club_admin/post'
  get 'club_admin/event_report'

  get 'admin/validate_club'
  get 'admin/post_announcements'
  post 'admin/do_post'
  get 'admin/accept'
  get 'admin/deny'

  resources :club, only: [:new, :create, :show, :update]

  resources :students, only: [:new, :create, :show, :update]

  resources :event, only: [:new, :create, :show, :update]

  root 'home#index'
  match '/signup',  to: 'students#new',            via: 'get'

end

app/models/bearer.rb
class Bearer < ActiveRecord::Base
  belongs_to :club
  validates :club_id, presence: true
  validates :name, presence: true, length: {maximum: 50}
  validates :phone, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
end

app/models/club.rb
class Club < ActiveRecord::Base
  mount_uploader :avatar, ClubAvatarUploader
  has_many :bearers
  has_many :club_posts
  has_many :club_events
  has_many :announcements
  before_save { self.club_login = club_login.downcase }
  validates :club_name, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: false}
  validates :club_number, presence: true
  validates :club_login, presence: true, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: {minimum: 6}

  def self.search(query)
    where("club_name like ?", "%#{query}%")
  end
end

app/models/club_event.rb
class ClubEvent < ActiveRecord::Base
  belongs_to :club
  belongs_to :event

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/club_post.rb
class ClubPost < ActiveRecord::Base
  belongs_to :club
  validates :post, presence: true, length: {maximum: 250}
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :club_events
  has_many :tickets
  has_many :student_tickets
  has_many :feedbacks

  mount_uploader :img1, EventImgUploader
  mount_uploader :img2, EventImgUploader
  mount_uploader :img3, EventImgUploader

  def self.search(query)
    where("title like ?", "%#{query}%")
  end

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :event
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :student_tickets
  has_many :feedbacks

  mount_uploader :avatar, StudentAvatarUploader
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :first_name, presence: true, length: {maximum: 50}
  validates :last_name, presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, length: {minimum: 6}

  def Student.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Student.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

  def create_remember_token
    self.remember_token = Student.digest(Student.new_remember_token)
  end


end

app/models/student_ticket.rb
class StudentTicket < ActiveRecord::Base
  belongs_to :student
  belongs_to :ticket
  belongs_to :event
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :event
  has_many :student_tickets
end

app/controllers/club_controller.rb
class ClubController < ApplicationController
  def new
    please_sign_in
    @club = Club.new
  end

  def create
    @club = Club.new(club_params)
    num_bearers = params.to_a[-4][0].split('_')[1]
    if @club.save
      i = 0
      while i < Integer(num_bearers) do
        no = i + 1
        is_administrator = false
        if params['bearer_' + no.to_s + '_admin'].to_s != ""
          is_administrator = true
        end
        Bearer.create(name: params['bearer_' + no.to_s + '_name'],
                      phone: params['bearer_' + no.to_s + '_phone'],
                      email: params['bearer_' + no.to_s + '_email'],
                      position: params['bearer_' + no.to_s + '_position'],
                      is_administrator: is_administrator, club_id: @club.id)
        i += 1
      end
      redirect_to @club
    else
      render 'new'
    end
  end

  def update
    @club = Club.find(session[:club_id])
    if @club.update_attributes(club_params)
      session[:success] = "Details updated successfully !"
      redirect_to club_admin_club_edit_path
    else
      render 'club_admin/club_edit'
    end
  end

  def show
    @club = Club.find(params[:id])
    @club_events = @club.club_events
    @events = Array.new
    if @club_events.count > 0
      @club_events.each do |ce|
        @events.append(Event.find(ce.event_id))
      end
    end
  end

  private
  def club_params
    params.require(:club).permit(:club_name, :club_number, :url, :club_login, :password, :password_confirmation, :avatar)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Clubbiz"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/club_admin_helper.rb
module ClubAdminHelper
  def club_signed_in?
    !session[:club_id].nil?
  end

  def club_please_sign_in
    if session[:club_id].nil?
      redirect_to club_admin_club_login_path
    end
  end
end

app/helpers/club_helper.rb
module ClubHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/event_share_helper.rb
module EventShareHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(student)
    remember_token = Student.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    student.update_attribute(:remember_token, Student.digest(remember_token))
    self.current_student = student
  end

  def current_student=(student)
    @current_student = student
  end

  def current_student
    remember_token = Student.digest(cookies[:remember_token])
    @current_student ||= Student.find_by(remember_token: remember_token)
  end

  def signed_in?
    !current_student.nil?
  end

  def sign_out
    current_student.update_attribute(:remember_token,
                                     Student.digest(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_student = nil
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/admin/post_announcements.html.erb
<% provide(:title, 'Administration - Post Announcements') %>
<div id="content">
  <div class="inner-content" id="myContent">
    <div class="single-box">
      <div class="project-post-content">
        <%= render 'shared/Admin/admin_nav_bar' %>
        <h1>Post announcements to all clubs</h1>
        <%= render 'shared/ClubAdmin/club_update_success' %>
        <div class="text-fields newfont">
          <%= form_tag (admin_do_post_path) do %>
              <span><i class="fa fa-paper-plane"></i></span>
              <label for="announcement">Content</label>
              <textarea id="announcement" class="form-control" maxlength="250" name="announcement" rows="5" required></textarea>
              <br>
              <p align="center"><%= submit_tag "Post", class: "btn btn-success btn-lg" %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/validate_club.html.erb
<% provide(:title, 'Administration - Validate Clubs') %>
<div id="content">
  <div class="inner-content" id="myContent">
    <div class="single-box">
      <div class="project-post-content">
        <%= render 'shared/Admin/admin_nav_bar' %>
        <h1>Validate Registered Clubs</h1>

        <div class="text-fields newfont">
          <br>
          <% @club.each do |club| %>
              <p align="center">Name: <%= club.club_name %> - Number: <%= club.club_number %>

                <%= link_to "Accept", "accept?id=" + club.id.to_s, class: "btn btn-success" %>
                <%= link_to "Deny", "deny?id=" + club.id.to_s, class: "btn btn-danger" %></p>
          <% end %>
          <% if @club.count == 0 %>
              <p align="center">There is no club need to be validated.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>