config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  get 'search/do_search'
  post 'search/do_search'

  get 'reserve_ticket/reserve'
  post 'reserve_ticket/do_reserve'

  get 'event_share/share'
  post 'event_share/do_share'
  post 'event_share/post_feedback'

  get 'student_admin/student_login'
  get 'student_admin/student_edit'
  get 'student_admin/logout'
  post 'student_admin/login'

  get 'club_admin/club_edit'
  get 'club_admin/club_post'
  get 'club_admin/club_login'
  post 'club_admin/login'
  get 'club_admin/logout'
  post 'club_admin/post'
  get 'club_admin/event_report'

  get 'admin/validate_club'
  get 'admin/post_announcements'
  post 'admin/do_post'
  get 'admin/accept'
  get 'admin/deny'

  resources :club, only: [:new, :create, :show, :update]

  resources :students, only: [:new, :create, :show, :update]

  resources :event, only: [:new, :create, :show, :update]

  root 'home#index'
  match '/signup',  to: 'students#new',            via: 'get'

end

app/controllers/club_admin_controller.rb
class ClubAdminController < ApplicationController
  def club_edit
    if session[:club_id].nil?
      redirect_to club_admin_club_login_path
    else
      @club = Club.find(session[:club_id])
    end
  end

  def club_post
    if session[:club_id].nil?
      redirect_to club_admin_club_login_path
    else
      @club = Club.find(session[:club_id])
    end
  end

  def event_report
    @club = Club.find(session[:club_id])
    @club_events = @club.club_events
    @event = Array.new
    if @club_events.count > 0
      @club_events.each do |ce|
        @event.append(Event.find(ce.event_id))
      end
    end
  end

  def post
    if ClubPost.create(post: params[:post_content], club_id: session[:club_id])
      session[:success] = "Announcement posted successfully !"
      redirect_to club_admin_club_post_path
    end
  end

  def club_login
    if !session[:club_id].nil?
      @club = Club.find(session[:club_id])
      redirect_to @club
    end
  end

  def login
    @login_error = nil

    login_id = params[:club_login_id].to_s.downcase
    password = params[:password].to_s
    club = Club.find_by_club_login(login_id)
    if club && club.authenticate(password) && club.club_valid
      session[:club_id] = club.id
      redirect_to club_admin_club_edit_path
    else
      if club
        if club.club_valid.nil?
          @club_not_valid = 1
        end
        if club.club_valid == false
          @club_not_validated = 1
        end
      else
        @login_error = true
      end

      render 'club_login'
    end
  end

  def logout
    session[:club_id] = nil
    redirect_to club_admin_club_login_path
  end

end

app/helpers/club_admin_helper.rb
module ClubAdminHelper
  def club_signed_in?
    !session[:club_id].nil?
  end

  def club_please_sign_in
    if session[:club_id].nil?
      redirect_to club_admin_club_login_path
    end
  end
end

app/views/club_admin/club_edit.html.erb
<% provide(:title, @club.club_name + ' Management') %>
<div id="content">
  <div class="inner-content" id="myContent">
    <div class="single-box">
      <div class="project-post-content">
        <%= render 'shared/ClubAdmin/club_admin_nav_bar' %>
        <h1>Update <%= @club.club_name %>'s details</h1>
        <%= render 'shared/Club/club_reg_error_messages' %>
        <%= render 'shared/ClubAdmin/club_update_success' %>
        <div class="text-fields newfont">
          <%= form_for @club, html: {multipart: true} do |f| %>
              <span><i class="fa fa-group"></i></span> <%= f.label :club_name, "Club Name" %>
              <%= f.text_field :club_name, class: "form-control" %>

              <span><i class="fa fa-barcode"></i></span><%= label_tag :club_number, "Club Registration No" %>
              <%= f.text_field :club_number, class: "form-control" %>

              <span><i class="fa fa-globe"></i></span><%= label_tag :url, "Club Website" %>
              <%= f.text_field :url, class: "form-control" %>

              <span><i class="fa fa-image"></i></span><%= label_tag :avatar, "Club Avatar" %>
              <%= f.file_field :avatar, class: "form-control" %>

              <span><i class="fa fa-user"></i></span> <%= label_tag :club_login, "Club Login ID" %>
              <%= f.text_field :club_login, class: "form-control" %>

              <span><i class="fa fa-lock"></i></span><%= label_tag :password, "Password" %>
              <%= f.password_field :password, class: "form-control" %>

              <span><i class="fa fa-lock"></i></span> <%= label_tag :password_confirmation, "Password Confirmation" %>
              <%= f.password_field :password_confirmation, class: "form-control" %>

              <p align="center"> <%= submit_tag "Update", class: "btn btn-warning btn-lg" %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/club_admin/club_login.html.erb
<% provide(:title, 'Club Sign In') %>
<div id="content">
  <div class="inner-content" id="myContent">
    <div class="single-box">
      <div class="project-post-content">
        <h1>Sign In to Manage Your Club</h1>
        <%= render 'shared/ClubAdmin/club_login_error' %>
        <div class="text-fields newfont">
          <%= form_tag (club_admin_login_path) do %>
              <span><i class="fa fa-user"></i></span><%= label_tag :club_login_id, "Club Login ID" %>
              <%= text_field_tag :club_login_id, nil, class: "form-control", required: '' %>

              <span><i class="fa fa-lock"></i></span><%= label_tag :password, "Password" %>
              <%= password_field_tag :password, nil, class: "form-control", required: '' %>
              <br>

              <p align="center"><%= submit_tag "Sign In", class: "btn btn-success btn-lg" %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/club_admin/club_post.html.erb
<% provide(:title, @club.club_name + ' Management') %>
<div id="content">
  <div class="inner-content" id="myContent">
    <div class="single-box">
      <div class="project-post-content">
        <%= render 'shared/ClubAdmin/club_admin_nav_bar' %>
        <h1>Post Announcements</h1>
        <%= render 'shared/ClubAdmin/club_update_success' %>
        <div class="text-fields newfont">

          <%= form_tag (club_admin_post_path) do %>
              <span><i class="fa fa-paper-plane"></i></span>
              <label for="post_content">Content</label>
              <textarea id="post_content" class="form-control" maxlength="250" name="post_content" rows="5" required></textarea>
              <br>

              <p align="center"><%= submit_tag "Post", class: "btn btn-success btn-lg" %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/club_admin/event_report.html.erb
<% provide(:title, @club.club_name + ' Management') %>
<div id="content">
  <div class="inner-content" id="myContent">
    <div class="single-box">
      <div class="project-post-content">
        <%= render 'shared/ClubAdmin/club_admin_nav_bar' %>
        <h1>Events Report</h1>
        <%= render 'shared/ClubAdmin/club_update_success' %>
        <div class="text-fields newfont">
        <% if @event.count == 0 %>
        <br>
        <p align="center"><%= "This club has not created any event." %></p>
        <% else %>
        <% @event.each do |e| %>
            <%= link_to e.title, e,  style: "font-size: 20px; font-weight: bold; color: #c0392b; text-decoration: none"%>
            <div class="rounded-box">
            <p>Total Participants: <%= e.student_tickets.sum('amount') %> persons</p>
            <p>Total Earned: <%= e.student_tickets.sum('paid') %>$</p>
            </div>
        <% end %>
        <% end %>
        </div>
      </div>
    </div>
  </div>
</div>