config/routes.rb
Rails.application.routes.draw do

  get 'home/index'

  get 'search/do_search'
  post 'search/do_search'

  get 'reserve_ticket/reserve'
  post 'reserve_ticket/do_reserve'

  get 'event_share/share'
  post 'event_share/do_share'
  post 'event_share/post_feedback'

  get 'student_admin/student_login'
  get 'student_admin/student_edit'
  get 'student_admin/logout'
  post 'student_admin/login'

  get 'club_admin/club_edit'
  get 'club_admin/club_post'
  get 'club_admin/club_login'
  post 'club_admin/login'
  get 'club_admin/logout'
  post 'club_admin/post'
  get 'club_admin/event_report'

  get 'admin/validate_club'
  get 'admin/post_announcements'
  post 'admin/do_post'
  get 'admin/accept'
  get 'admin/deny'

  resources :club, only: [:new, :create, :show, :update]

  resources :students, only: [:new, :create, :show, :update]

  resources :event, only: [:new, :create, :show, :update]

  root 'home#index'
  match '/signup',  to: 'students#new',            via: 'get'

end

app/controllers/club_admin_controller.rb
class ClubAdminController < ApplicationController
  def club_edit
    if session[:club_id].nil?
      redirect_to club_admin_club_login_path
    else
      @club = Club.find(session[:club_id])
    end
  end

  def club_post
    if session[:club_id].nil?
      redirect_to club_admin_club_login_path
    else
      @club = Club.find(session[:club_id])
    end
  end

  def event_report
    @club = Club.find(session[:club_id])
    @club_events = @club.club_events
    @event = Array.new
    if @club_events.count > 0
      @club_events.each do |ce|
        @event.append(Event.find(ce.event_id))
      end
    end
  end

  def post
    if ClubPost.create(post: params[:post_content], club_id: session[:club_id])
      session[:success] = "Announcement posted successfully !"
      redirect_to club_admin_club_post_path
    end
  end

  def club_login
    if !session[:club_id].nil?
      @club = Club.find(session[:club_id])
      redirect_to @club
    end
  end

  def login
    @login_error = nil

    login_id = params[:club_login_id].to_s.downcase
    password = params[:password].to_s
    club = Club.find_by_club_login(login_id)
    if club && club.authenticate(password) && club.club_valid
      session[:club_id] = club.id
      redirect_to club_admin_club_edit_path
    else
      if club
        if club.club_valid.nil?
          @club_not_valid = 1
        end
        if club.club_valid == false
          @club_not_validated = 1
        end
      else
        @login_error = true
      end

      render 'club_login'
    end
  end

  def logout
    session[:club_id] = nil
    redirect_to club_admin_club_login_path
  end

end

app/helpers/club_admin_helper.rb
module ClubAdminHelper
  def club_signed_in?
    !session[:club_id].nil?
  end

  def club_please_sign_in
    if session[:club_id].nil?
      redirect_to club_admin_club_login_path
    end
  end
end

app/views/shared/ClubAdmin/_club_admin_nav_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header" style="font-family: 'Existence-Light', Arial, sans-serif;">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">Club Management</span>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li
        <% if params[:action] == "show" && params[:controller] == "club" %>class="active"
        <% end %>>
          <a href=<%= "/club/#{@club.id}" %>><b>Club's Profile</b></a></li>
        <li
        <% if params[:action] == "club_edit" %>class="active"
        <% end %>>
          <a href=<%= club_admin_club_edit_path %>><b>Update Details</b></a></li>
        <li
        <% if params[:action] == "club_post" %>class="active"
        <% end %>>
          <a href=<%= club_admin_club_post_path %>><b>Post Announcement</b></a></li>

        <li
        <% if params[:controller] == "event" %>class="active"
        <% end %>>
          <a href=<%= new_event_path %>><b>Create Event</b></a></li>

        <li
        <% if params[:action] == "event_report" %>class="active"
        <% end %>>
          <a href=<%= club_admin_event_report_path %>><b>Event's Report</b></a></li>


      </ul>
      <a class="btn btn-danger navbar-btn pull-right" href=<%= club_admin_logout_path %>>Sign Out</a>

    </div>

  </div>

</nav>
<div><%= render 'shared/ClubAdmin/club_announcement' %></div>

app/views/shared/ClubAdmin/_club_announcement.html.erb
<% if @club.announcement %>
    <div id="error_explanation">
      <div class="alert alert-info newfont">
        <h4>Announcement from Administrator</h4>
        <%= @club.announcement %>
      </div>
    </div>
<% end %>

app/views/shared/ClubAdmin/_club_login_error.html.erb
<% if !@login_error.nil? %>
    <div id="error_explanation">
      <div class="alert alert-danger newfont">
        Wrong Login ID or Password.
      </div>
    </div>
<% end %>
<% if !@club_not_valid.nil? %>
    <div id="error_explanation">
      <div class="alert alert-danger newfont">
        Your club is not valid and is not able to function in this website.
      </div>
    </div>
<% end %>
<% if !@club_not_validated.nil? %>
    <div id="error_explanation">
      <div class="alert alert-danger newfont">
        Your club is not yet validated by the administrator. Please wait.
      </div>
    </div>
<% end %>

app/views/shared/ClubAdmin/_club_update_success.html.erb
<% if session[:success] %>
    <div id="error_explanation">
      <div class="alert alert-success newfont">
        <%= session[:success] %>
      </div>
    </div>
    <% session[:success] = nil %>
<% end %>